# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: Ubuntu-DevOps-Practices
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Build versionized'

- script: |
    ng add @ng-toolkit/universal
    ng add @ng-toolkit/serverless  —-provider aws
    npm run build:serverless:deploy
    env
    sudo cp -rf /home/ubuntu/DevOps-practices/work-place/1/s/* /home/ubuntu/DevOps-practices/work-place-2
    sudo rm -rf /home/ubuntu/DevOps-practices/work-place/1/s/*
  displayName: 'Build steps'
 
- task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
  displayName: 'S3 Upload: digital-api-angular-universal-serverless-deploy'
  inputs:
    awsCredentials: 'aws-admin-devops-practices'
    regionName: 'us-east-2'
    bucketName: 'digital-api-angular-universal-serverless-deploy'
    sourceFolder: '/home/ubuntu/DevOps-practices/work-place/1/s/'
    globExpressions: browser.zip
    targetFolder: deployable
    createBucket: true
