# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: Ubuntu-EC2-UE1
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Build versionized'

- script: |
    ng add @ng-toolkit/universal
    ng add @ng-toolkit/serverless  —-provider aws
    npm run build:serverless:deploy
    env
    sudo cp -rf /home/ubuntu/DevOps/_work/* /home/ubuntu/DevOps/_work2/
    sudo rm -rf /home/ubuntu/DevOps/_work/*
  displayName: 'Build steps'
